#!/bin/bash

# Make sure we avoid running multiple instances of this script

LOCKFILE="/var/lock/`basename $0`"
LOCKFD=99

# PRIVATE
_lock()             { flock -$1 $LOCKFD; }
_no_more_locking()  { _lock u; _lock xn && rm -f $LOCKFILE; }
_prepare_locking()  { eval "exec $LOCKFD>\"$LOCKFILE\""; trap _no_more_locking EXIT; }

# ON START
_prepare_locking

# PUBLIC
exlock_now()        { _lock xn; }  # obtain an exclusive lock immediately or fail
exlock()            { _lock x; }   # obtain an exclusive lock
shlock()            { _lock s; }   # obtain a shared lock
unlock()            { _lock u; }   # drop a lock

# CHECK
exlock_now || exit 1

# PROGRAM
logfile="/var/log/rcloned.log"
IFS="|"

/usr/sbin/sysctl fs.inotify.max_user_watches=1048576; 
/usr/sbin/sysctl fs.inotify.max_queued_events=2097152;

localDirectory='"/dataEncrypted/Folder 1/" "/dataEncrypted/Folder 2/"'
excludedPathOnRemote="/dataEncrypted"
remoteRclonePath="acd:"
pipe="/tmp/rcloned"
touch $pipe

echo "Watching: $localDirectory";

io="inotifywait -m -r -e close_write --exclude '(/~|\.tmp|\.bak|\.TMP|\.BAK)' --timefmt '%d/%m/%y|%H:%M:%S' --format '%T|%w|%f' $localDirectory"
echo "Executing: $io";

eval "$io" |
    while read "date" "time" "dir" "file"; do
        echo "date='$date' time='$time' dir='$dir' file='$file'";
        local="\"$dir$file\""
        remote="$(echo $dir | perl -p -i -e "s|^$excludedPathOnRemote||g")"
        remote="\"$remoteRclonePath$remote\""
        grep -q "$local $remote" "$pipe" || ( echo "$local $remote" >> "$pipe"; touch $logfile; echo "`date` - rclonedWatcher: $local $remote" >> "$logfile" )
    done;

exit;
